export const ADD_SYMBOL = 'ADD_SYMBOL'
export const CLEAR_LAST_OPERAND='CLEAR_LAST_OPERAND'
export const SET_OPERATOR='SET_OPERATOR'
export const CLEAR_ALL='CLEAR_ALL'

export const NUMBER_1='1'
export const NUMBER_2='2'
export const NUMBER_3='3'
export const NUMBER_4='4'
export const NUMBER_5='5'
export const NUMBER_6='6'
export const NUMBER_7='7'
export const NUMBER_8='8'
export const NUMBER_9='9'
export const NUMBER_0='0'
export const AC='AC'
export const CE='CE'
export const PLUS='+'
export const MINUS='-'
export const MULTIPLY='*'
export const DEVIDE='/'
export const POINT='.'
export const RESULT='='


